ktor {
    deployment {
        port = 8081
        host = "0.0.0.0"
    }
    application {
        modules = [ com.example.server.ServerMainKt.module ]
    }
}

database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/fieldforce"
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = "asef"
    password = ${?DB_PASSWORD}
}
